:wrench: add first post
GDG-Nantes/devfest2017 pull request #32
Opened 2017-02-07 18:39 UTC by xavmarc

2017-02-07 18:40 UTC, xavmarc commented
#9

2017-02-08 07:23 UTC, pguyard requested changes

2017-02-08 07:23 UTC, pguyard commented on data/posts/2017-02-10-devfest-2017-announced.markdown
> +* Et pleins d’autres surprises et nouveautés qui vont seront présentées dans nos communications futures !
qui vous

2017-02-09 07:41 UTC, pguyard approved these changes

2017-02-09 07:42 UTC, merged