:sparkles: add pratique page
GDG-Nantes/devfest2017 pull request #37
Opened 2017-02-10 20:11 UTC by xavmarc

2017-02-10 20:28 UTC, xavmarc commented
#17

2017-02-11 13:01 UTC, jlandure requested changes

2017-02-11 13:01 UTC, jlandure commented on data/en/resources.json
> +  "location-pratique-title": "Where is the event ?",
pas d'espace en anglais sur la ponctuation: `Where is the event?`

2017-02-11 13:01 UTC, jlandure commented on data/en/resources.json
> +  "transport-pratique-title": "How to get there ?",
`How to get there?`

2017-02-11 13:33 UTC, jlandure approved these changes

2017-02-11 13:33 UTC, merged

2017-02-13 21:03 UTC, pguyard commented
Le texte parle des 2 hôtels mais il n'y a que la description de residhome !